/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ClockFace {
    'hour': number;
    'minute': number;
    'second': number;
  }
  interface MyComponent {}
  interface TimeZoneSlider {
    'offset': number;
  }
}

declare global {


  interface HTMLClockFaceElement extends Components.ClockFace, HTMLStencilElement {}
  var HTMLClockFaceElement: {
    prototype: HTMLClockFaceElement;
    new (): HTMLClockFaceElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLTimeZoneSliderElement extends Components.TimeZoneSlider, HTMLStencilElement {}
  var HTMLTimeZoneSliderElement: {
    prototype: HTMLTimeZoneSliderElement;
    new (): HTMLTimeZoneSliderElement;
  };
  interface HTMLElementTagNameMap {
    'clock-face': HTMLClockFaceElement;
    'my-component': HTMLMyComponentElement;
    'time-zone-slider': HTMLTimeZoneSliderElement;
  }
}

declare namespace LocalJSX {
  interface ClockFace {
    'hour'?: number;
    'minute'?: number;
    'second'?: number;
  }
  interface MyComponent {}
  interface TimeZoneSlider {
    'offset'?: number;
    'onTimeZoneChanged'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'clock-face': ClockFace;
    'my-component': MyComponent;
    'time-zone-slider': TimeZoneSlider;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'clock-face': LocalJSX.ClockFace & JSXBase.HTMLAttributes<HTMLClockFaceElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'time-zone-slider': LocalJSX.TimeZoneSlider & JSXBase.HTMLAttributes<HTMLTimeZoneSliderElement>;
    }
  }
}


